# Generated by Django 3.1.3 on 2021-01-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activite_stud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='act',
            new_name='Activity',
        ),
    ]
