# Generated by Django 3.1.3 on 2021-01-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='forumdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
