# Generated by Django 3.1.3 on 2021-01-08 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_comments_commentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentdate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 8, 2, 50, 27, 697861), null=True),
        ),
    ]
