# Generated by Django 3.1.3 on 2021-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='About',
            field=models.TextField(default='None', max_length=500, null=True),
        ),
    ]
