# Generated by Django 3.1.3 on 2021-01-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Teacher_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
