# Generated by Django 3.1.3 on 2021-01-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210106_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='HourRate',
            field=models.IntegerField(default='25', null=True),
        ),
    ]
