# Generated by Django 3.1.3 on 2021-01-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_hourrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='LessonMethod',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('Frontal', 'Frontal')], default=True, max_length=100),
        ),
    ]
