# Generated by Django 3.1.3 on 2020-12-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ImageField(default=1, upload_to='homepage/images/'),
            preserve_default=False,
        ),
    ]
