# Generated by Django 3.1.3 on 2021-01-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='home/images/defult.png', upload_to='home/images'),
        ),
    ]
