# Generated by Django 3.1.3 on 2020-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ImageField(default='book_catalog/images/defult.png', upload_to='homepage/images/'),
        ),
    ]
