# Generated by Django 3.1.3 on 2021-01-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210103_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='book_catalog/images/defult2.png', upload_to='home/images'),
        ),
    ]
