# Generated by Django 3.1.3 on 2020-12-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201228_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
