# Generated by Django 3.1.3 on 2020-12-28 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_homepage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
