# Generated by Django 3.1.3 on 2021-01-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20210103_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='homepage/images/defult2.jpg', upload_to='home/images'),
        ),
    ]
