# Generated by Django 3.1.3 on 2020-12-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20201228_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='time',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='date',
            field=models.DateField(blank=True, default=1),
        ),
    ]
