# Generated by Django 3.1.3 on 2020-12-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20201228_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='date',
            field=models.DateField(),
        ),
    ]
