# Generated by Django 3.1.3 on 2021-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20210103_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(default='book_catalog/images/defult.png', upload_to='home/images')),
                ('events', models.ManyToManyField(blank=True, null=True, to='homepage.Event')),
            ],
        ),
    ]
