# Generated by Django 3.1.3 on 2021-01-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_event_registerstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='change_Book_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
