# Generated by Django 3.1.3 on 2020-12-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_homepage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='date',
            field=models.DateField(default=False),
        ),
    ]
