# Generated by Django 3.1.3 on 2021-01-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_event_change_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='change_Book_date',
        ),
        migrations.AddField(
            model_name='homepage',
            name='change_Book_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
