# Generated by Django 3.1.3 on 2020-12-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20201228_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='date',
        ),
    ]
