# Generated by Django 3.1.3 on 2021-01-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_auto_20210108_0221'),
        ('homepage', '0012_auto_20210104_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registerstudent',
            field=models.ManyToManyField(blank=True, to='authentication.Student'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='events',
            field=models.ManyToManyField(blank=True, to='homepage.Event'),
        ),
    ]
