# Generated by Django 3.1.3 on 2021-01-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0021_auto_20210103_2220'),
        ('review', '0003_remove_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, to='book_catalog.Book'),
        ),
    ]
