# Generated by Django 3.1.3 on 2021-01-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0027_book_take_date'),
        ('review', '0004_auto_20210105_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_catalog.book'),
            preserve_default=False,
        ),
    ]
