# Generated by Django 3.1.3 on 2021-01-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0027_book_take_date'),
        ('review', '0005_auto_20210107_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_catalog.book'),
        ),
    ]
