# Generated by Django 3.1.3 on 2021-01-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0028_auto_20210107_2204'),
        ('review', '0007_auto_20210107_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ManyToManyField(blank=True, to='book_catalog.Book'),
        ),
    ]
