# Generated by Django 3.1.3 on 2020-12-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20201228_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='taz',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
