# Generated by Django 3.1.3 on 2020-12-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201228_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='type',
            field=models.CharField(default='Adult', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
