# Generated by Django 3.1.3 on 2020-12-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20201230_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='IsBanned',
            field=models.BooleanField(default=False),
        ),
    ]
