# Generated by Django 3.1.3 on 2020-12-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_student_isbanned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='IsBanned',
            new_name='Forum_Banned',
        ),
        migrations.AddField(
            model_name='adult',
            name='Is_Banned',
            field=models.BooleanField(default=False),
        ),
    ]
