# Generated by Django 3.1.3 on 2020-12-30 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20201230_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Phone_Number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
