# Generated by Django 3.1.3 on 2020-12-30 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='Is_Banned',
            field=models.BooleanField(default=False, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
