# Generated by Django 3.1.3 on 2020-12-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20201230_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='Security_Check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='Security_Check',
            field=models.BooleanField(default=False),
        ),
    ]
