# Generated by Django 3.1.3 on 2020-12-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0011_auto_20201130_2307'),
        ('authentication', '0015_auto_20201230_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='FavouriteBooks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_catalog.book'),
        ),
    ]
