# Generated by Django 3.1.3 on 2020-12-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0011_auto_20201130_2307'),
        ('authentication', '0016_adult_favouritebooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adult',
            name='FavouriteBooks',
        ),
        migrations.AddField(
            model_name='adult',
            name='FavouriteBooks',
            field=models.ManyToManyField(null=True, to='book_catalog.Book'),
        ),
    ]
