# Generated by Django 3.1.3 on 2020-12-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20201230_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='Is_Banned',
            field=models.BooleanField(default=False),
        ),
    ]
