# Generated by Django 3.1.3 on 2020-12-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0011_auto_20201130_2307'),
        ('authentication', '0018_auto_20201230_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='FavouriteBooks',
            field=models.ManyToManyField(blank=True, null=True, to='book_catalog.Book'),
        ),
    ]
