# Generated by Django 3.1.3 on 2020-12-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0014_remove_book_posses'),
        ('authentication', '0019_auto_20201230_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='Adultposses',
            field=models.ManyToManyField(blank=True, null=True, related_name='posses', to='book_catalog.Book'),
        ),
        migrations.AddField(
            model_name='student',
            name='Studentposses',
            field=models.ManyToManyField(blank=True, null=True, to='book_catalog.Book'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='FavouriteBooks',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite', to='book_catalog.Book'),
        ),
    ]
