# Generated by Django 3.1.3 on 2020-12-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0015_book_posses'),
        ('authentication', '0020_auto_20201230_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='Adultposses',
            field=models.ManyToManyField(blank=True, null=True, related_name='adultposses', to='book_catalog.Book'),
        ),
    ]
