# Generated by Django 3.1.3 on 2021-01-05 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20201230_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='Is_Banned',
            field=models.BooleanField(default=False, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
