# Generated by Django 3.1.3 on 2021-01-05 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20210105_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='ID_Number',
            field=models.CharField(default=None, max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='adult',
            name='Is_Banned',
            field=models.BooleanField(default=False),
        ),
    ]
