# Generated by Django 3.1.3 on 2021-01-05 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20210105_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='ID_Number',
            field=models.CharField(default=None, max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
