# Generated by Django 3.1.3 on 2021-01-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_adult_reviews'),
        ('authentication', '0024_auto_20210105_2120'),
    ]

    operations = [
    ]
