# Generated by Django 3.1.3 on 2021-01-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_merge_20210106_1838'),
        ('authentication', '0026_auto_20210106_2208'),
    ]

    operations = [
    ]
