# Generated by Django 3.1.3 on 2021-01-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0028_auto_20210107_2204'),
        ('review', '0007_auto_20210107_1804'),
        ('authentication', '0027_merge_20210107_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='Adultposses',
            field=models.ManyToManyField(blank=True, related_name='adultposses', to='book_catalog.Book'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='FavouriteBooks',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='book_catalog.Book'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='review.Review'),
        ),
    ]
