# Generated by Django 3.1.3 on 2020-11-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Roman', 'Roman'), ('Fantasy', 'Fantasy')], default=True, max_length=100),
        ),
    ]
