# Generated by Django 3.1.3 on 2020-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0002_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Roman', 'Roman'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Poetry', 'Poetry'), ('Short story', 'Short story'), ('Thriller', 'Thriller'), ('Science fiction', 'Science fiction'), ('Horror', 'Horror'), ('Fairytale', 'Fairytale'), ('Comic book', 'Comic book'), ('Adventure', 'Adventure'), ('Food', 'Food')], default=True, max_length=100),
        ),
    ]
