# Generated by Django 3.1.3 on 2020-11-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0003_auto_20201130_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
