# Generated by Django 3.1.3 on 2020-11-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0006_remove_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_catalog/images/defult', upload_to='book_catalog/images'),
        ),
    ]
