# Generated by Django 3.1.3 on 2020-11-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0009_auto_20201130_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='librarianfavourite',
            field=models.BooleanField(default=False),
        ),
    ]
