# Generated by Django 3.1.3 on 2020-12-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0012_book_pusses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pusses',
            new_name='posses',
        ),
    ]
