# Generated by Django 3.1.3 on 2020-12-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0013_auto_20201230_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='posses',
        ),
    ]
