# Generated by Django 3.1.3 on 2020-12-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0015_book_posses'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='takenout',
            field=models.BooleanField(default=False),
        ),
    ]
