# Generated by Django 3.1.3 on 2021-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0016_book_takenout'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isdamaged',
            field=models.BooleanField(default=False),
        ),
    ]
