# Generated by Django 3.1.3 on 2021-01-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0017_book_isdamaged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isdamaged',
            new_name='Is_Damaged',
        ),
    ]
