# Generated by Django 3.1.3 on 2021-01-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0019_book_damage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
