# Generated by Django 3.1.3 on 2021-01-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0021_auto_20210103_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='length',
        ),
    ]
