# Generated by Django 3.1.3 on 2021-01-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0022_remove_book_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='adult_only',
            field=models.BooleanField(default=False),
        ),
    ]
