# Generated by Django 3.1.3 on 2021-01-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0023_book_adult_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kids',
            field=models.BooleanField(default=False),
        ),
    ]
