# Generated by Django 3.1.3 on 2021-01-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0024_book_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Grade',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=None, max_length=100, null=True),
        ),
    ]
