# Generated by Django 3.1.3 on 2021-01-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0026_auto_20210106_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Take_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
