# Generated by Django 3.1.3 on 2021-01-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0027_book_take_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('length', models.IntegerField(blank=True, default=None, max_length=100, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('reader_name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(default='book_catalog/images/defult.png', upload_to='book_catalog/images')),
                ('key_words', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Drama', 'Drama'), ('Roman', 'Roman'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Poetry', 'Poetry'), ('Short story', 'Short story'), ('Thriller', 'Thriller'), ('Science fiction', 'Science fiction'), ('Horror', 'Horror'), ('Fairytale', 'Fairytale'), ('Comic book', 'Comic book'), ('Adventure', 'Adventure'), ('Food', 'Food'), ('Study Book', 'Study Book')], default=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='reader_name',
        ),
    ]
